# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "Server1",
      :box => "bento/ubuntu-24.04",
      :box_version => "202502.21.0",
      :ip => "172.16.1.50",
      :ssh_port => '2200'
    },
    {
      :hostname => "Server2",
      :box => "bento/ubuntu-24.04",
      :ip => "172.16.1.51",
      :ssh_port => '2201'
    },
    {
      :hostname => "Server3",
      :box => "bento/ubuntu-24.04",
      :ip => "172.16.1.52",
      :ssh_port => '2202'
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.box_version = machine[:box_version] if machine[:box_version]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
      node.vm.synced_folder "../data", "/home/vagrant/data"
      node.vm.provision "file", source: "copyfile.txt", destination: "/home/vagrant/copyfile.txt"
      node.vm.provision "file", source: "text.txt", destination: "/home/vagrant/text.txt"
      node.vm.provision "shell", inline: "echo Hello from Server #{machine[:hostname]}"

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
    end
  end
end
